services:
  app:
    build: ./
    env_file: 'backend.env'
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-dockermodelrunner}
      - OPENAI_BASE_URL=${BASE_URL:-http://host.docker.internal:12434/engines/llama.cpp/v1/}
      - MODEL=${MODEL:-ai/llama3.2}
    ports:
      - "8501:8501"
    depends_on:
      - llm

  llm:
    provider:
      type: model
      options:
        model: ${MODEL:-ai/llama3.2}